### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by astrojuanlu** [pydata/bottleneck#388]
It looks like there was an attempt to release bottleneck 1.3.3 https://github.com/pydata/bottleneck/pull/347 but it didn't reach PyPI. Since #306 hasn't been released yet, users are finding all sorts of installation problems in Python 3.9, see #376. This will continue happening with the release of Python 3.10.

Even if the package is now unmaintained or dormand, if a new release is made with #306, at least some common installation issues will be addressed.

cc @qwhelan

**Comment by rubendibattista** [comment]
Ehi @qwhelan, is there any chance we might enlarge the maintainer cohort for this project? At least for housekeeping related things?  There are some problems with installation with `pip` I'd like to see resolved.

**Comment by marscher** [comment]
@shoyer Thousands of users would be delighted, if we could start using Python-3.10 for our projects depending on bottleneck. Is there still an active maintainer?

**Comment by shoyer** [comment]
I'd love to hear from @qwhelan here, who last I heard was taking over for Keith Goodman. Seems like adding additional maintainers could be a good idea if there are any volunteers.

**Comment by marscher** [comment]
Pushing releases to conda forge and PyPI seems not too much of a burden for me. I just have to admit, that I do not know anything about this code-base and release pipeline. But it also looks like the CI needs some fix ups too.

**Comment by rubendibattista** [comment]
I can also take care of the housekeeping of the package not related to the "math". I use the package at work, it would be directly useful for us.

**Comment by stroxler** [comment]
I'd be happy to help with housekeeping as well, particularly if we just need more people who can act as reviewers.

**Comment by marscher** [comment]
So it seems there is no lack for volunteers, so we should proceed and choose somebody, right?

**Comment by qwhelan** [comment]
I've sent invites to @rdbisme and @stroxler for the GitHub account - I'll need PyPI accounts as well to give upload rights.

Apologies for the lag in responding to this issue, I've had zero free bandwidth between work and personal matters as of late.

**Comment by rdbisme** [comment]
> I've sent invites to @rdbisme and @stroxler for the GitHub account - I'll need PyPI accounts as well to give upload rights.
> 
> Apologies for the lag in responding to this issue, I've had zero free bandwidth between work and personal matters as of late.

Thanks for the trust!

**Comment by stroxler** [comment]
@qwhelan Thanks!

Sorry for the delay - my PyPi account is user `stroxler` (same as my github account).

**Comment by rdbisme** [comment]
Just to give some visibility on what we've been doing after being promoted maintainer of the project:

After a chat with @qwhelan introducing the current situation on the project, the `master` branch is not release-ready. @qwhelan was working on fixing some inconsistencies wrt numpy summation that are in a good state of advancement, but not finished. So in order to provide a new release the fastest possible in order to push fixes for Python 3.10 and whatsoever, We will organize the work as following:

 

1. Move the current code into a separate `develop` branch

2. Revert the code to just after latest release

3. Cherry-pick/apply most important fixes to allow a hot-fix release to cover most impelling problems downstream

4. Fix and unify as much as possible CI (Suggestions welcome. Personally, I have strong experience with Gitlab CI and fair experience with Github Actions. Maybe Azure pipelines might provide wider coverage in terms of architecture / systems)

5. Release a new bugfix release

6. Rebase `develop` on top of the new tagged state

7. Keep working on improvements.

 

Let us know what do you think.

**Comment by marscher** [comment]
Github actions also provides windows/osx arch support, so no need to hassle with Azure.

**Comment by rdbisme** [comment]
Hello, I just released a pre-release version with pre-compiled wheels for most architectures. Can you give it a go? 

```
pip install --pre "bottleneck==1.3.3rc13"
```

**Comment by marscher** [comment]
It works on Linux, 64bit, Python 3.10

**Comment by marscher** [comment]
Thank you so much!

**Comment by TradingMax** [comment]
> Hello, I just released a pre-release version with pre-compiled wheels for most architectures. Can you give it a go?
> 
> ```
> pip install --pre "bottleneck==1.3.3rc13"
> ```
> 
> PS: Should I include wheels or not?

Thank you for the effort and time to volunteer to pick this up, I would be very grateful if wheels could be included in releases. 

This would be of great help to many users (including those who are not bothering to turn up here and simply choosing to drop installing bottleneck as an optional dependency for pandas). Largely the user base is split into two (my best guess) those who have no idea how to set up building and those who can't build due to corporate/educational environment restrictions. Also it was noted that during CI process it takes some time to build and a wheel would be extremely helpful to speed this process up.

I'm just getting to grips with CI and as such can't provide much assistance except just say thank you for reading and taking it into consideration.

**Comment by rdbisme** [comment]
> > Hello, I just released a pre-release version with pre-compiled wheels for most architectures. Can you give it a go?
> > ```
> > pip install --pre "bottleneck==1.3.3rc13"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: Should I include wheels or not?
> 
> Thank you for the effort and time to volunteer to pick this up, I would be very grateful if wheels could be included in releases.
> 
> This would be of great help to many users (including those who are not bothering to turn up here and simply choosing to drop installing bottleneck as an optional dependency for pandas). Largely the user base is split into two (my best guess) those who have no idea how to set up building and those who can't build due to corporate/educational environment restrictions. Also it was noted that during CI process it takes some time to build and a wheel would be extremely helpful to speed this process up.
> 
> I'm just getting to grips with CI and as such can't provide much assistance except just say thank you for reading and taking it into consideration.

Hello @TradingMax. Wheels have been included starting from v1.3.3 for x86_64. Therefore, installing v1.3.3+ should smooth on most machines (beware that probably using wheels will reduce the benefits from CPU-specific optimizations). I plan to add wheel for ARM in the future, just need to understand how to do that with Github Actions and in the mid / long term dynamical dispatching to ship into the the pre-compiled wheels all the possible optimized libraries and dispatch the most appropriate one based on CPU features.

**Comment by rdbisme** [comment]
Hello, if anyone in this conversation would like to help with maintaining the project, this issue might be interesting for you: https://github.com/pydata/bottleneck/issues/424
